### ISSUE TITLE
Others ways People will be wrong

### ISSUE THREAD

**Issue by lopestom** [smith901/bluvivoxl2twrp3#1]
https://plus.google.com/u/0/+AntonioLopes_lopestom/posts/8TApPrP9fns

**Comment by smith901** [comment]
That guide is for a **BLU Studio XL2**, not the **BLU Vivo XL2**. Not an issue on my part.  Nice information, not helpful to anyone with a **BLU Vivo XL2**.
It is not permanent, mine is.  **Work on your own issues before claiming issues with mine.  File it with yourself.**

**Comment by lopestom** [comment]
Smith, this is not to issue, claiming or other question....
That's only to you know about v3.1 for your device can have........
Allways that I can, so im only showning something for better............

> Work on your own issues before claiming issues with mine. File it with yourself.

Sorry, But we have some problem?? Well, i think NO!!
Have a nice day........ 
Closed!!  **MINDED**

By Me: It is not **PERMANENT OR FOR THE VIVO XL2**  therefore it is not better.  Your touch doesn't work.  I'm fully working with encryption.  I don't need my SD card to be formatted a certain way.  Anyone I pop in will work.  Your "whatever it is you are trying to show me" is limited.  Work on your stuff, Fuck off My page.
